# Much of this script was adapted from astropy/astropy.

sudo: false

addons:
    apt:
        packages:
            - libeigen3-dev

language: python
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
    - NUMPY_VERSION=1.8
    - NUMPY_VERSION=1.9

install:
    - pip install -q numpy==$NUMPY_VERSION
    - pip install -q scipy nose Cython PyYAML jinja2
    - CXX=g++ python setup.py build_ext --inplace

script:
    - nosetests -v
