sudo: false
language: python
addons:
    apt:
        packages:
            - libeigen3-dev
env:
    global:
        - NUMPY_VERSION=1.12

matrix:
    include:
        # All the versions of Python.
        - python: 2.7
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.11
        - python: 2.7
          env: NUMPY_VERSION=1.12
        - python: 3.4
          env: NUMPY_VERSION=1.11
        - python: 3.5
          env: NUMPY_VERSION=1.12
        - python: 3.6
          env: NUMPY_VERSION=1.11
        - python: 3.6
          env: NUMPY_VERSION=1.12

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION scipy nose pip Cython
    - CXX=g++ python setup.py build_ext --inplace

script:
    - nosetests -v
